extends: photo.j2
default_block: post
listable: true
album_cover: San_Francisco_-_Skyline_at_Night
title: San Francisco
description: >
    Spent the weekend in San Francisco with friends before I started classes.
created: !!timestamp 2013-01-18 00:00:00
