extends: photo.j2
default_block: post
listable: true
album_cover: San_Francisco/San_Francisco_-_Skyline_at_Night
title: California Photos
description: >
    Photos of my trip to California in January 2013
created: !!timestamp 2013-01-20 00:00:00
